apiVersion: v1
kind: Secret
metadata:
  name: event-schedule-secret
  namespace: event-schedule
type: Opaque
stringData:
  MONGODB_URI: "mongodb://mongo-service:27017/event-schedule"
  # Replace with your PostHog key if using analytics
  NEXT_PUBLIC_POSTHOG_KEY: ""
